FROM node:20-alpine

WORKDIR /usr/src/app

ARG DATABASE_URL
COPY package.json package-lock.json* ./
COPY turbo.json ./turbo.json
COPY ./packages ./packages
COPY ./apps/web ./apps/web

RUN npm install
RUN npm run db:generate
RUN DATABASE_URL=${DATABASE_URL} npm run build

EXPOSE 3000

CMD ["npm", "run", "start:web"]
